"""api_key token_encrypted

Revision ID: fae8db738539
Revises: 75887d8488b0
Create Date: 2026-08-02 03:48:41.815744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fae8db738539'
down_revision: Union[str, None] = '75887d8488b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('token_encrypted', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'token_encrypted')
    # ### end Alembic commands ###
